version: '3.9'

services:
  db_writingor_theme:
    image: mariadb:latest
    volumes:
      - db_data_writingor_theme:/var/lib/mysql
    restart: always
    environment:
      MARIADB_DATABASE: wordpress_writingor_theme
      MARIADB_ROOT_PASSWORD: password

  wordpress_writingor_theme:
    depends_on:
      - db_writingor_theme
    image: wordpress:latest
    volumes:
      - wordpress_data_writingor_theme:/var/www/html
      - ./public:/var/www/html/wp-content/themes/writingor_theme
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - '8002:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db_writingor_theme
      WORDPRESS_DB_NAME: wordpress_writingor_theme
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password

volumes:
  db_data_writingor_theme: {}
  wordpress_data_writingor_theme: {}
  